server:
  port: 8093

spring:
  application:
    name: sales-service
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:easyops}
    username: ${DB_USER:easyops}
    password: ${DB_PASSWORD:easyops123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: sales
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: sales
    locations: classpath:db/migration
    validate-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true

logging:
  level:
    com.easyops.sales: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Service URLs for Feign clients
services:
  accounting:
    url: ${ACCOUNTING_SERVICE_URL:http://localhost:8080}
  ar:
    url: ${AR_SERVICE_URL:http://localhost:8090}
  notification:
    url: ${NOTIFICATION_SERVICE_URL:http://localhost:8095}

# Sales Service Configuration
sales:
  quotation:
    validity-days: 30
    auto-number-prefix: "QT"
  order:
    auto-number-prefix: "SO"
    require-approval: false
    approval-amount-threshold: 10000

