server:
  port: 8081

spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-management
          uri: lb://user-management-service
          predicates:
            - Path=/api/users/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: rbac-service
          uri: lb://rbac-service
          predicates:
            - Path=/api/rbac/**
        - id: system-config
          uri: lb://system-config-service
          predicates:
            - Path=/api/system/**
        - id: monitoring-service
          uri: lb://monitoring-service
          predicates:
            - Path=/api/monitoring/**
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/api/organizations/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**, /api/webhooks/**
        - id: accounting-service
          uri: lb://accounting-service
          predicates:
            - Path=/api/accounting/**
        - id: ar-service
          uri: lb://ar-service
          predicates:
            - Path=/api/ar/**
        - id: ap-service
          uri: lb://ap-service
          predicates:
            - Path=/api/ap/**
        - id: bank-service
          uri: lb://bank-service
          predicates:
            - Path=/api/bank/**
        - id: sales-service
          uri: lb://sales-service
          predicates:
            - Path=/api/sales/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_LAST
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: 
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# JWT Configuration
jwt:
  secret: easyops-jwt-secret-key-change-this-in-production-minimum-256-bits
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.easyops: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

logging:
  level:
    root: INFO
    com.easyops: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN
    com.easyops: INFO
  file:
    name: logs/api-gateway.log
