services:
  ap-service:
    build:
      context: .
      dockerfile: services/ap-service/Dockerfile.dev
      args:
        - MAVEN_OPTS=-Xmx2048m -Dmaven.wagon.http.retryHandler.count=5 -Dmaven.wagon.http.retryHandler.requestSentEnabled=true -Dmaven.wagon.http.retryHandler.delay=2000
    environment:
      - MAVEN_OPTS=-Xmx2048m -Dmaven.wagon.http.retryHandler.count=5 -Dmaven.wagon.http.retryHandler.requestSentEnabled=true -Dmaven.wagon.http.retryHandler.delay=2000
    volumes:
      # Mount Maven local repository to persist dependencies
      - maven-cache:/root/.m2
volumes:
  maven-cache:
    driver: local
