server:
  port: 8095

spring:
  application:
    name: purchase-service
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:easyops}
    username: ${DB_USER:easyops}
    password: ${DB_PASSWORD:easyops123}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: purchase
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    show-sql: false
  
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: 6379
    password: ${SPRING_REDIS_PASSWORD:}
  
  cache:
    type: none

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: false
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.easyops.purchase: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

