spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:5432/${DB_NAME:easyops}
    username: ${DB_USER:easyops}
    password: ${DB_PASSWORD:easyops123}
  
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka:8761/eureka}

logging:
  level:
    com.easyops.purchase: DEBUG

