spring:
  application:
    name: rbac-service-test
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis

logging:
  level:
    com.easyops: INFO
    org.springframework: WARN
    org.hibernate: WARN

