spring:
  application:
    name: automation-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/easyops
    username: easyops
    password: easyops123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: accounting
  
  cache:
    type: redis
  
  data:
    redis:
      host: redis
      port: 6379
      timeout: 60000
  
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: AutomationScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: false
            dataSource: quartzDataSource
            tablePrefix: QRTZ_
            isClustered: true
          dataSource:
            quartzDataSource:
              driver: org.postgresql.Driver
              URL: jdbc:postgresql://localhost:5432/easyops
              user: easyops
              password: easyops123

server:
  port: 8094

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# Management & Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    defaults:
      enabled: true

# Logging Configuration
logging:
  level:
    com.easyops: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
    org.quartz: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Automation Service Configuration
automation:
  recurring:
    enabled: true
    check-interval: "0 0 1 * * ?" # Run daily at 1 AM
  posting:
    auto-determine-accounts: true
    validate-before-post: true
  execution:
    max-retries: 3
    retry-delay: 5000 # milliseconds

