spring:
  application:
    name: monitoring-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/easyops
    username: easyops
    password: easyops123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: system

server:
  port: 8087

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# Management & Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    defaults:
      enabled: true

# Logging Configuration
logging:
  level:
    com.easyops: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Monitoring Configuration
monitoring:
  health-check:
    interval-seconds: 30
    timeout-seconds: 5
  metrics:
    retention-days: 30
  alerts:
    enabled: true

